eureka:
    instance:
      preferredIp: true
    client:
      register-with-eureka: true
      fetch-registry: true
      serviceUrl:
        default-zone: ${EUREKA_URL:http://localhost:8761/eureka}
